
const employee = require("./employee")
const job_title = require("./job_title")
const gender = require("./gender")
const grade = require("./grade")
const catu = require("./catu")
const approval = require("./approval")
const approval_transaction = require("./approval_transaction")
const approval_type = require("./approval_type")
const employee_status = require("./employee_status")
const employee_status_tax = require("./employee_status_tax")
const employee_salary_system = require("./employee_salary_system")
const employee_type = require("./employee_type")
const employee_marital = require("./employee_marital")
const department = require("./department")
const education = require("./education")
const religion = require("./religion")
const login = require("./login")
const company = require("./company")
const company_type = require("./company_type")
const token = require("./token")
const menu = require("./menu")
const menu_mobile = require("./menu_mobile")
const language = require("./language")
const users = require("./users")
const attendance_machine = require("./attendance_machine")
const ateendance_employee = require("./ateendance_employee")
const working_hours = require("./working_hours")
const employee_assign = require("./employee_assign")
const employee_assign_report = require("./employee_assign_report")
const item_master = require("./item_master")
const item_category = require("./item_category")
const purchase_request = require("./purchase_request")
const purchase_request_approval = require("./purchase_request_approval")
const partners = require("./partners")
const partners_type = require("./partners_type")
const term_of_payment = require("./term_of_payment")
const receiving_locations = require("./receiving_locations")
const purchase_request_quotation = require("./purchase_request_quotation")
const purchase_order = require("./purchase_order")
const posting = require("./posting")
const posting_type = require("./posting_type")
const signature = require("./signature")
const coa = require("./coa")
const goods_receipt_warehouse = require("./goods_receipt_warehouse")
const goods_receipt_asset = require("./goods_receipt_asset")
const goods_receipt_approval = require("./goods_receipt_approval")
const asset_type = require("./asset_type")
const asset_subtype = require("./asset_subtype")
const asset = require("./asset")
const warehouse = require("./warehouse")
const activity_type = require("./activity_type")
const activity = require("./activity")
const purchase_request_report = require("./purchase_request_report")
const trial_balance_report = require("./trial_balance_report")
const journal = require("./journal")
const goods_issue = require("./goods_issue")
const goods_issue_approval = require("./goods_issue_approval")
const payment_voucher_type = require("./payment_voucher_type")
const accounting_periods = require("./accounting_periods")
const payment_voucher = require("./payment_voucher")
const bank_account = require("./bank_account")
const cash_bank = require("./cash_bank")
const transaction_unposting = require("./transaction_unposting")
const seed_type = require("./seed_type")
const block_master = require("./block_master")
const harvest_penalty_type = require("./harvest_penalty_type")
const harvest_penalty = require("./harvest_penalty")
const harvest_incentive = require("./harvest_incentive")
const average_bunch_rate = require("./average_bunch_rate")
const basic_salary = require("./basic_salary")
const holiday = require("./holiday")
const natura = require("./natura")
const estate_activity = require("./estate_activity")
const mill_oprations = require("./mill_oprations")


const controller = {};

controller.employee = employee;
controller.job_title = job_title;
controller.gender = gender;
controller.grade = grade;
controller.catu = catu;
controller.approval = approval;
controller.approval_transaction = approval_transaction;
controller.approval_type = approval_type;
controller.employee_status = employee_status;
controller.employee_status_tax = employee_status_tax;
controller.employee_salary_system = employee_salary_system;
controller.employee_type = employee_type;
controller.employee_marital = employee_marital;
controller.department = department;
controller.education = education;
controller.religion = religion;
controller.login = login;
controller.company = company;
controller.company_type = company_type;
controller.token = token;
controller.menu = menu;
controller.menu_mobile = menu_mobile;
controller.language = language;
controller.users = users;
controller.attendance_machine = attendance_machine;
controller.ateendance_employee = ateendance_employee;
controller.working_hours = working_hours;
controller.employee_assign = employee_assign;
controller.employee_assign_report = employee_assign_report;
controller.item_master = item_master;
controller.item_category = item_category;
controller.purchase_request = purchase_request;
controller.purchase_request_approval = purchase_request_approval;
controller.partners = partners;
controller.partners_type = partners_type;
controller.term_of_payment = term_of_payment;
controller.receiving_locations = receiving_locations;
controller.purchase_request_quotation = purchase_request_quotation;
controller.purchase_order = purchase_order;
controller.posting = posting;
controller.posting_type = posting_type;
controller.signature = signature;
controller.coa = coa;
controller.goods_receipt_warehouse = goods_receipt_warehouse;
controller.goods_receipt_asset = goods_receipt_asset;
controller.goods_receipt_approval = goods_receipt_approval;
controller.asset_type = asset_type;
controller.asset_subtype = asset_subtype;
controller.asset = asset;
controller.warehouse = warehouse;
controller.activity_type = activity_type;
controller.activity = activity;
controller.purchase_request_report = purchase_request_report;
controller.trial_balance_report = trial_balance_report;
controller.journal = journal;
controller.goods_issue = goods_issue;
controller.goods_issue_approval = goods_issue_approval;
controller.payment_voucher_type = payment_voucher_type;
controller.accounting_periods = accounting_periods;
controller.payment_voucher = payment_voucher;
controller.bank_account = bank_account;
controller.cash_bank = cash_bank;
controller.transaction_unposting = transaction_unposting;
controller.seed_type = seed_type;
controller.block_master = block_master;
controller.harvest_penalty_type = harvest_penalty_type;
controller.harvest_penalty = harvest_penalty;
controller.harvest_incentive = harvest_incentive;
controller.average_bunch_rate = average_bunch_rate;
controller.basic_salary = basic_salary;
controller.holiday = holiday;
controller.natura = natura;
controller.estate_activity = estate_activity;
controller.mill_oprations = mill_oprations;


module.exports = controller;
